name: Deploy
on:
  push:
    branches:
      - '*'
jobs:
  deploy-master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment:
      name: 'main'
    steps:
      - name: instalar git
        run: sudo apt install git -y

      - name: instalar tar
        run: sudo apt install tar -y

      - name: Eliminar antes de clonar
        run : sudo rm -rf /opt/deploy/
        #run : sudo rm -rf ${{secrets.PATH}} 

      - name: Crear carpeta con día y hora
        run: sudo mkdir /opt/deploy/
        #run: sudo mkdir ${{secrets.PATH}} 

      - name: Ir a carpeta con día y hora
        run: cd /opt/deploy/
        #run: cd ${{secrets.PATH}}

      - name: permisos en otra ruta
        run: sudo chmod 777 /opt/deploy/
        #run: sudo chmod 777 ${{secrets.PATH}}

      - name: Clonar Repositorio
        run:  git clone https://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@github.com/Samuelcloud07/java-tomcat-maven-example.git /opt/deploy/
        #run:  git clone https://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@github.com/Samuelcloud07/java-tomcat-maven-example.git ${{secrets.PATH}}

      #- name: Set up JDK 17
       # uses: actions/setup-java@v3
        # with:
          # java-version: '17'
          # distribution: 'temurin'
          # cache: maven
          
      #- name: Set up Maven
       # uses: aahmed-se/setup-maven@v3
        # with:
         #  maven-version: 3.6.1
          
     # - name: Setup Maven Action
      #  uses: s4u/setup-maven-action@v1.8.0

      #- name: version mvn
       # run: mvn -version

      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
           with:
           distribution: 'temurin'
           java-version: '17'
           cache: 'maven'
        - name: Build with Maven
          run: mvn -B package --file pom.xml

      - name: entrar el projecto & build
        run : |
                cd  /opt/deploy/java-tomcat-maven-example
                mvn package

      - name: Pasar el war        
        run : |
                  cp java-tomcat-maven-example.war /opt/deploy/tomcat/webapps/
                
